apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-deployment
  labels:
    app: connect-app
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: connect-app
      environment: dev
  template:
    metadata:
      labels:
        app: connect-app
        environment: dev
    spec:
      containers:
      - name: connect-container
        image: docker-ids-dim-release.dr-uw2.adobeitc.com/cp-kafka-connect:5.3.1
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "or1010051053014.corp.adobe.com:9092"
        - name: CONNECT_GROUP_ID
          value: "connect-cluster-dev"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "connect-status"
        - name: CONNECT_KEY_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://schema-registry-service:8081"
        - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
          value: "true"
        - name: CONNECT_VALUE_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://schema-registry-service:8081"
        - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "true"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java"
        # This is required to avoid config bugs. You should set this to a value that is
        # resolvable by all containers.
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "connect"
        - name: CONNECT_REST_PORT
          value: "8083"
        ports:
        - containerPort: 8081
        volumeMounts:
          - name: krb5-keytab
            mountPath: /etc/security/keytabs
      hostname: connect
      imagePullSecrets:
      - name: registrypullsecret
      restartPolicy: Always
      volumes:
      - name: krb5-keytab
        persistentVolumeClaim:
          claimName: keytab-pv-claim
