apiVersion: v1
kind: Service
metadata:
  labels:
    service: rest-proxy-np
    environment: dev
  name: rest-proxy-np
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30082
  selector:
    app: rest-proxy
    environment: dev
  sessionAffinityConfig: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
