apiVersion: v1
kind: Service
metadata:
  labels:
    service: rest-proxy-service
    environment: dev
  name: rest-proxy-service-dev
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: rest-proxy-app
    environment: dev
  sessionAffinityConfig: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
