apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-proxy-deployment
  labels:
    app: rest-proxy-app
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-proxy-app
      environment: dev
  template:
    metadata:
      labels:
        app: rest-proxy-app
        environment: dev
    spec:
      containers:
      - name: rest-proxy-container
        image: docker-ids-dim-release.dr-uw2.adobeitc.com/cp-kafka-rest:5.3.1
        env:
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: "or1010051053014.corp.adobe.com:2181"
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "or1010051053014.corp.adobe.com:9092"
        - name: KAFKA_REST_HOST_NAME
          value: "rest-proxy"
        - name: KAFKA_REST_LISTENERS
          value: "http://0.0.0.0:8082"
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: "http://schema-registry-service-dev:8081"
        - name: KAFKA_REST_ID
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8082
      hostname: rest-proxy
      imagePullSecrets:
      - name: registrypullsecret
      restartPolicy: Always
