apiVersion: v1
kind: Service
metadata:
  labels:
    service: schema-registry-service
    environment: dev
  name: schema-registry-service-dev
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: schema-registry-app
    environment: dev
  sessionAffinityConfig: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
