apiVersion: v1
kind: Service
metadata:
  labels:
    service: schema-registry
    environment: dev
  name: schema-registry-np
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: schema-registry
    environment: dev
  sessionAffinityConfig: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
