apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keytab-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local-storage
