apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-volume
  labels:
    type: local-storage
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  local:
    path: "/data2/k8s"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - or1hdp1095.corp.adobe.com
